---
- name: apt-get updates a server
  apt: update_cache=yes
  sudo: yes
  tags: initial_setup

- name: apt-get upgrade a server
  apt: upgrade=full
  sudo: yes
  tags: initial_setup

- name: apt-get install basic pkg
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
  - nkf
  - git
  - gcc
  - g++
  - automake
  - libtool
  - autoconf
  - patch
  - subversion
  - lynx
  - graphviz
  - bc
  - vim
  - bzip2 
  - wget
  - pciutils 
  - libatlas3-base 
  - zlib1g-dev 
  - make 
  tags: initial_setup
