---
- name: update blacklist-nouveau.conf 
  lineinfile: >
    dest="/etc/modprobe.d/blacklist-nouveau.conf"
    create=yes
    line="{{ item.line }}"
  with_items:
  - line: blacklist nouveau 
  - line: blacklist lbm-nouveau 
  - line: options nouveau modeset=0 
  - line: alias nouveau off 
  - line: alias lbm-nouveau off 
  sudo: yes
  tags: configure nouveau 

- name: remake nouveau 
  shell: echo options nouveau modeset=0 | sudo tee -a /etc/modprobe.d/nouveau-kms.conf 
  sudo: yes
  tags: configure nouveau 

- name: update 
  shell: update-initramfs -u 
  sudo: yes
  tags: update 

- name: reboot!
  command: shutdown -r now
  sudo: yes
  ignore_errors: true
  tags: reboot

