---
- name: apt-get install basic pkg
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
  - gridengine-master 
  - gridengine-client 
  - subversion 
  tags: initial_setup
- name: Download grid Engine 
  command: svn cat https://svn.code.sf.net/p/kluster/code/trunk/scripts/sbin/mem-killer.pl > /sbin/mem-killer.pl 
  sudo: yes
  tags: grid engine 
- name: Install gridEngine 
  command: chmod +x /sbin/mem-killer.pl 
  sudo: yes
  tags: gridEngine Install
- name: Install gridEngine2 
  command: cd /etc/init.d 
  sudo: yes
  tags: gridEngine Install2
- name: Install gridEngine3 
  command: svn cat https://svn.code.sf.net/p/kluster/code/trunk/scripts/etc/init.d/mem-killer >mem-killer
  sudo: yes
  tags: gridEngine Install3
- name: Install gridEngine4 
  command: chmod +x mem-killer 
  sudo: yes
  tags: gridEngine Install4
- name: Install gridEngine5 
  command: update-rc.d mem-killer defaults 
  sudo: yes
  tags: gridEngine Install5
- name: Install gridEngine6 
  command: service mem-killer start 
  sudo: yes
  tags: gridEngine Install6
